import { utilService } from '../util.service'
// import { httpService } from '../http.service'
import { storageService } from '../async-storage.service'

const KEY = 'board_db'

const ENDPOINT = 'board'
// const BASE_URL =
//   process.env.NODE_ENV !== 'development' ? '/api/board' : '//localhost:3030/api/board/'

export const boardService = {
  query,
  getBoardById,
  remove,
  save,
  getNewBoard,
  getNewPlayer,
}

// const gBoards = _createBoards()

async function query(filterBy = {}) {
  // return await httpService.get(ENDPOINT, filterBy)
  return storageService.query(KEY)
}

async function getBoardById(boardId) {
  // return await httpService.get(`${ENDPOINT}/${boardId}`)
  return storageService.getById(KEY, boardId)
}

async function remove(boardId) {
  // return await httpService.delete(`${ENDPOINT}/${boardId}`)
  return storageService.remove(KEY, boardId)
}

async function save(board) {
  // return board._id
  //   ? await httpService.put(`${ENDPOINT}/${board._id}`, board)
  //   : await httpService.post(ENDPOINT, board)
  return board._id
    ? storageService.put(KEY, board)
    : storageService.post(KEY, board)
}

function getNewBoard(players) {
  return Promise.resolve({
    // _id: 'b-' + utilService.makeId(),
    name: 'New-board',
    createdAt: new Date(),
    tokens: [
      {
        name: 'Scottish Terrier',
      },
      {
        name: 'Battleship',
      },
      {
        name: 'race car mid',
      },
      {
        name: 'Top Hat',
      },
      {
        name: 'Penguin',
      },
      {
        name: 'T-Rex',
      },
      {
        name: 'Cat',
      },
      {
        name: 'Rubber Ducky',
      },
    ],
    houses: 32,
    hotels: 12,
    doubleCount: 0,
    currPLayer: players[0] || null,
    players,
    tiles: [
      {
        name: 'START',
        players,
        owner: null,
        price: 60,
        type: 'go',
      },
      {
        name: 'KOMPLEK A CIRACAS',
        players: [],
        owner: null,
        color: '#562e22',
        price: 2320,
        type: 'city',
      },
      {
        name: 'Community chest',
        players: [],
        owner: null,
        color: '',
        type: 'communityChest',
      },
      {
        name: 'KOMPLEK B SUSUKAN',
        players: [],
        owner: null,
        color: '#562e22',
        price: 4640,
        type: 'city',
      },
      {
        name: 'Pajak penghasilan bayar',
        players: [],
        owner: null,
        color: '',
        price: 1000,
        type: 'tax',
      },
      {
        name: 'Reading Railroad',
        players: [],
        owner: null,
        color: '',
        price: 200,
        type: 'railroad',
      },
      {
        name: 'KOMPLEK C CIJANTUNG',
        players: [],
        owner: null,
        color: '#95b8cb',
        price: 1610,
        type: 'city',
      },
      {
        name: 'Chance',
        players: [],
        owner: null,
        type: 'chance',
      },
      {
        name: 'KOMPLEK D CIPAYUNG',
        players: [],
        owner: null,
        color: '#95b8cb',
        price: 3480,
        type: 'city',
      },
      {
        name: 'KOMPLEK E CILANGKAP',
        players: [],
        owner: null,
        color: '#95b8cb',
        price: 2320,
        type: 'city',
      },
      {
        name: 'jail',
        players: [],
        owner: null,
        type: 'visit',
      },
      {
        name: 'KOMPLEK F CILILITAN',
        players: [],
        owner: null,
        color: '#cb5382',
        price: 1610,
        type: 'city',
      },
      {
        name: 'Pajak Penerang Jalan',
        players: [],
        owner: null,
        color: '',
        price: 150,
        type: 'tax',
      },
      {
        name: 'KOMPLEK G RAMBUTAN',
        players: [],
        owner: null,
        color: '#cb5382',
        price: 3480,
        type: 'city',
      },
      {
        name: 'KOMPLEK H KRAMAT JATI',
        players: [],
        owner: null,
        color: '#cb5382',
        price: 4640,
        type: 'city',
      },
      {
        name: 'Pennsylvania Railroad',
        players: [],
        owner: null,
        color: '',
        price: 200,
        type: 'railroad',
      },
      {
        name: 'KOMPLEK I KALISARI',
        players: [],
        owner: null,
        color: '#ffa600',
        price: 2320,
        type: 'city',
      },
      {
        name: 'Community chest',
        players: [],
        owner: null,
        type: 'communityChest',
      },
      {
        name: 'KOMPLEK J CAKUNG',
        players: [],
        owner: null,
        color: '#ffa600',
        price: 2320,
        type: 'city',
      },
      {
        name: 'KOMPLEK K CAWANG',
        players: [],
        owner: null,
        color: '#ffa600',
        price: 1610,
        type: 'city',
      },

      {
        name: 'Parking',
        players: [],
        owner: null,
        color: '',
        type: 'parking',
      },
      {
        name: 'KOMPLEK L CONDET',
        players: [],
        owner: null,
        color: '#cf3b30',
        price: 5800,
        type: 'city',
      },
      {
        name: 'Chance',
        players: [],
        owner: null,
        color: '',
        type: 'chance',
      },
      {
        name: 'KOMPLEK M PASAR REBO',
        players: [],
        owner: null,
        color: '#cf3b30',
        price: 4640,
        type: 'city',
      },
      {
        name: 'KOMPLEK N PASAR SENIN',
        players: [],
        owner: null,
        color: '#cf3b30',
        price: 2320,
        type: 'city',
      },
      {
        name: 'B. & O. Railroad',
        players: [],
        owner: null,
        color: '',
        price: 200,
        type: 'railroad',
      },
      {
        name: 'KOMPLEK O KP.MELAYU',
        players: [],
        owner: null,
        color: '#d3c11b',
        price: 3480,
        type: 'city',
      },
      {
        name: 'KOMPLEK P CIPINANG',
        players: [],
        owner: null,
        color: '#d3c11b',
        price: 4640,
        type: 'city',
      },
      {
        name: 'Pajak Rokok',
        players: [],
        owner: null,
        color: '',
        price: 150,
        type: 'tax',
      },
      {
        name: 'KOMPLEK Q CILANDAK',
        players: [],
        owner: null,
        color: '#d3c11b',
        price: 2320,
        type: 'city',
      },
      {
        name: 'Send To Jail',
        players: [],
        owner: null,
        color: '',
        type: 'jail',
      },
      {
        name: 'KOMPLEK R PEJATEN',
        players: [],
        owner: null,
        color: '#0ab842',
        price: 3100,
        type: 'city',
      },
      {
        name: 'KOMPLEK S GEDONG',
        players: [],
        owner: null,
        color: '#0ab842',
        price: 3600,
        type: 'city',
      },
      {
        name: 'Community chest',
        players: [],
        owner: null,
        color: '',
        type: 'communityChest',
      },
      {
        name: 'KOMPLEK T PS.MINGGU',
        players: [],
        owner: null,
        color: '#0ab842',
        price: 4640,
        type: 'city',
      },
      {
        name: 'Short Line',
        players: [],
        owner: null,
        color: '',
        price: 200,
        type: 'railroad',
      },
      {
        name: 'Chance',
        players: [],
        owner: null,
        color: '',
        type: 'chance',
      },
      {
        name: 'KOMPLEK U KALIBATA',
        players: [],
        owner: null,
        color: '#2863ad',
        price: 1160,
        type: 'city',
      },
      {
        name: 'Pajak Parkir',
        players: [],
        owner: null,
        color: '',
        price: 200,
        type: 'tax',
      },
      {
        name: 'KOMPLEK V JAGAKARSA',
        players: [],
        owner: null,
        color: '#2863ad',
        price: 3380,
        type: 'city',
      },
    ],
    cmpsOrder: [
      'startCmp',
      'tileCmp',
      'communityCmp',
      'tileCmp',
      'incomeCmp',
      'railroadCmp',
      'tileCmp',
      'chanceCmp',
      'tileCmp',
      'tileCmp',
      'jailCmp',
      'tileCmp',
      'electricCmp',
      'tileCmp',
      'tileCmp',
      'railroadCmp',
      'tileCmp',
      'communityCmp',
      'tileCmp',
      'tileCmp',
      'parkingCmp',
      'tileCmp',
      'chanceCmp',
      'tileCmp',
      'tileCmp',
      'railroadCmp',
      'tileCmp',
      'tileCmp',
      'waterWorkCmp',
      'tileCmp',
      'sendToJailCmp',
      'tileCmp',
      'tileCmp',
      'communityCmp',
      'tileCmp',
      'railroadCmp',
      'chanceCmp',
      'tileCmp',
      'luxuryTaxCmp',
      'tileCmp',
    ],
    cards: {
      propertyCards: [
        {
          _id: 'property-101',
          title: 'KOMPLEK A CIRACAS',
          color: '#562e22',
          price: 2320,
          rent: 1100,
          ddp: 2000,
          bphtb: 100,
          ppn: 220,
          pph: 50,
          oneHouse: 500,
          twoHouses: 1100,
          threeHouses: 1650,
          fourHouses: 2200,
          hotel: 250,
          mortgage: 30,
          houseCost: 50,
          hotelCost: 210,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 2,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-102',
          title: 'KOMPLEK B SUSUKAN',
          color: '#562e22',
          rent: 2300,
          ddp: 4000,
          bphtb: 200,
          ppn: 440, 
          pph: 100,
          price: 4640,
          oneHouse: 1000,
          twoHouses: 2200,
          threeHouses: 3300,
          fourHouses: 4400,
          hotel: 450,
          mortgage: 30,
          houseCost: 50,
          hotelCost: 370,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 2,
          houses: 0,
          hotels: 0,
        },

        {
          _id: 'property-103',
          title: 'KOMPLEK C CIJANTUNG',
          color: '#95b8cb',
          price: 1610,
          rent: 600,
          ddp: 1000,
          bphtb: 500,
          ppn: 110,
          pph: 40,
          oneHouse: 400,
          twoHouses: 880,
          threeHouses: 1320,
          fourHouses: 1760,
          hotel: 550,
          mortgage: 50,
          houseCost: 50,
          hotelCost: 450,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-104',
          title: 'KOMPLEK D CIPAYUNG',
          color: '#95b8cb',
          price: 3480,
          rent: 1600,
          ddp: 3000,
          bphtb: 150,
          ppn: 330,
          pph: 80,
          oneHouse: 800,
          twoHouses: 1760,
          threeHouses: 2640,
          fourHouses: 3520,
          hotel: 550,
          mortgage: 50,
          houseCost: 50,
          hotelCost: 450,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-105',
          title: 'KOMPLEK E CILANGKAP',
          color: '#95b8cb',
          price: 2320,
          rent: 1150,
          ddp: 2000,
          bphtb: 100,
          ppn: 220,
          pph: 50,
          oneHouse: 500,
          twoHouses: 1100,
          threeHouses: 1650,
          fourHouses: 2200,
          hotel: 600,
          mortgage: 60,
          houseCost: 50,
          hotelCost: 500,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-106',
          title: 'KOMPLEK F CILILITAN',
          color: '#cb5382',
          price: 1610,
          rent: 550,
          ddp: 1000,
          bphtb: 500,
          ppn: 110,
          pph: 60,
          oneHouse: 600,
          twoHouses: 1320,
          threeHouses: 1980,
          fourHouses: 2640,
          hotel: 750,
          mortgage: 70,
          houseCost: 100,
          hotelCost: 725,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-107',
          title: 'KOMPLEK G RAMBUTAN',
          color: '#cb5382',
          price: 3480,
          rent: 1640,
          ddp: 3000,
          bphtb: 150,
          ppn: 330,
          pph: 110,
          oneHouse: 1100,
          twoHouses: 2420,
          threeHouses: 3630,
          fourHouses: 4840,
          hotel: 750,
          mortgage: 70,
          houseCost: 100,
          hotelCost: 725,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-108',
          title: 'KOMPLEK H KRAMAT JATI',
          color: '#cb5382',
          price: 4640,
          rent: 2320,
          ddp: 4000,
          bphtb: 200,
          ppn: 440,
          pph: 100,
          oneHouse: 1000,
          twoHouses: 2200,
          threeHouses: 3300,
          fourHouses: 4400,
          hotel: 900,
          mortgage: 80,
          houseCost: 100,
          hotelCost: 800,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },

        {
          _id: 'property-109',
          title: 'KOMPLEK I KALISARI',
          color: '#ffa600',
          price: 2320,
          rent: 1110,
          ddp: 2000,
          bphtb: 100,
          ppn: 220,
          pph: 50,
          oneHouse: 500,
          twoHouses: 1100,
          threeHouses: 1650,
          fourHouses: 2200,
          hotel: 950,
          mortgage: 90,
          houseCost: 100,
          hotelCost: 850,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-110',
          title: 'KOMPLEK J CAKUNG',
          color: '#ffa600',
          price: 2320,
          rent: 1110,
          ddp: 2000,
          bphtb: 100,
          ppn: 220,
          pph: 80,
          oneHouse: 800,
          twoHouses: 1760,
          threeHouses: 2640,
          fourHouses: 3520,
          hotel: 950,
          mortgage: 90,
          houseCost: 100,
          hotelCost: 850,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-111',
          title: 'KOMPLEK K CAWANG',
          color: '#ffa600',
          price: 1610,
          rent: 553,
          ddp: 1000,
          bphtb: 500,
          ppn: 110,
          pph: 60,
          oneHouse: 600,
          twoHouses: 1320,
          threeHouses: 1980,
          fourHouses: 2640,
          hotel: 1000,
          mortgage: 100,
          houseCost: 100,
          hotelCost: 900,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-112',
          title: 'KOMPLEK L CONDET',
          color: '#cf3b30',
          price: 5800,
          rent: 2900,
          ddp: 5000,
          bphtb: 250,
          ppn: 550,
          pph: 150,
          oneHouse: 1500,
          twoHouses: 3300,
          threeHouses: 4950,
          fourHouses: 6600,
          hotel: 1050,
          mortgage: 110,
          houseCost: 150,
          hotelCost: 1025,
          hotelCostNotCalc: 150,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-113',
          title: 'KOMPLEK M PASAR REBO',
          color: '#cf3b30',
          price: 4640,
          rent: 2320,
          ddp: 4000,
          bphtb: 200,
          ppn: 440,
          pph: 100,
          oneHouse: 1000,
          twoHouses: 2200,
          threeHouses: 3300,
          fourHouses: 4400,
          hotel: 1050,
          mortgage: 110,
          houseCost: 150,
          hotelCost: 1025,
          hotelCostNotCalc: 150,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-114',
          title: 'KOMPLEK N PASAR SENIN',
          color: '#cf3b30',
          price: 2320,
          rent: 1110,
          ddp: 2000,
          bphtb: 100,
          ppn: 220,
          pph: 50,
          oneHouse: 500,
          twoHouses: 1100,
          threeHouses: 1650,
          fourHouses: 2200,
          hotel: 1100,
          mortgage: 120,
          houseCost: 150,
          hotelCost: 1075,
          hotelCostNotCalc: 150,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },

        {
          _id: 'property-115',
          title: 'KOMPLEK O KP.MELAYU',
          color: '#d3c11b',
          price: 3480,
          rent: 1690,
          ddp: 3000,
          bphtb: 150,
          ppn: 330,
          pph: 110,
          oneHouse: 1100,
          twoHouses: 2420,
          threeHouses: 3630,
          fourHouses: 4840,
          hotel: 1150,
          mortgage: 130,
          houseCost: 150,
          hotelCost: 1125,
          hotelCostNotCalc: 150,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-116',
          title: 'KOMPLEK P CIPINANG',
          color: '#d3c11b',
          price: 4640,
          rent: 2320,
          ddp: 4000,
          bphtb: 200,
          ppn: 440,
          pph: 100,
          oneHouse: 1000,
          twoHouses: 2200,
          threeHouses: 3300,
          fourHouses: 4400,
          hotel: 1150,
          mortgage: 130,
          houseCost: 150,
          hotelCost: 1125,
          hotelCostNotCalc: 150,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-117',
          title: 'KOMPLEK Q CILANDAK',
          color: '#d3c11b',
          price: 2320,
          rent: 1160,
          ddp: 2000,
          bphtb: 300,
          ppn: 20,
          pph: 100,
          oneHouse: 1000,
          twoHouses: 2200,
          threeHouses: 3300,
          fourHouses: 4400,
          hotel: 1200,
          mortgage: 140,
          houseCost: 150,
          hotelCost: 1175,
          hotelCostNotCalc: 150,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-118',
          title: 'KOMPLEK R PEJATEN',
          color: '#0ab842',
          price: 3100,
          rent: 1550,
          ddp: 2900,
          bphtb: 100,
          ppn: 100,
          pph: 130,
          oneHouse: 1300,
          twoHouses: 2300,
          threeHouses: 3300,
          fourHouses: 4300,
          hotel: 1275,
          mortgage: 150,
          houseCost: 200,
          hotelCost: 1300,
          hotelCostNotCalc: 200,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-119',
          title: 'KOMPLEK S GEDONG',
          color: '#0ab842',
          price: 3600,
          rent: 1750,
          ddp: 3400,
          bphtb: 100,
          ppn: 100,
          pph: 60,
          oneHouse: 600,
          twoHouses: 1200,
          threeHouses: 2200,
          fourHouses: 3300,
          hotel: 1275,
          mortgage: 150,
          houseCost: 200,
          hotelCost: 1300,
          hotelCostNotCalc: 200,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-120',
          title: 'KOMPLEK T PS.MINGGU',
          color: '#0ab842',
          price: 4640,
          rent: 2320,
          ddp: 4000,
          bphtb: 500,
          ppn: 140,
          pph: 110,
          oneHouse: 1100,
          twoHouses: 2200,
          threeHouses: 3300,
          fourHouses: 4400,
          hotel: 1400,
          mortgage: 160,
          houseCost: 200,
          hotelCost: 1400,
          hotelCostNotCalc: 200,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },

        {
          _id: 'property-121',
          title: 'KOMPLEK U KALIBATA',
          color: '#2863ad',
          price: 1160,
          rent: 580,
          ddp: 1000,
          bphtb: 100,
          ppn: 60,
          pph: 120,
          oneHouse: 1200,
          twoHouses: 2400,
          threeHouses: 3500,
          fourHouses: 4600,
          hotel: 1500,
          mortgage: 170,
          houseCost: 200,
          hotelCost: 1500,
          hotelCostNotCalc: 200,
          type: 'propertyCard',
          quantity: 2,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-122',
          title: 'KOMPLEK V JAGAKARSA',
          color: '#2863ad',
          price: 3380,
          rent: 1690,
          ddp: 3000,
          bphtb: 300,
          ppn: 80,
          pph: 110,
          oneHouse: 1100,
          twoHouses: 2250,
          threeHouses: 3250,
          fourHouses: 4350,
          hotel: 2000,
          mortgage: 200,
          houseCost: 200,
          hotelCost: 1900,
          hotelCostNotCalc: 200,
          type: 'propertyCard',
          quantity: 2,
          houses: 0,
          hotels: 0,
        },
      ],

      // utilitiesCards: [
      //   {
      //     _id: 'utility-101',
      //     title: 'Electric Company',
      //     price: 150,
      //     rent: '4 * Dice Roll',
      //     twoAreOwned: '10 * Dice Roll',
      //     mortgage: 75,
      //     background: '#cf8e61',
      //     type: 'utilityCard',
      //   },
      //   {
      //     _id: 'utility-102',
      //     title: 'Pajak Smoking',
      //     price: 150,
      //     rent: '4 * Dice Roll',
      //     twoAreOwned: '10 * Dice Roll',
      //     mortgage: 75,
      //     background: '#f6f4f4',
      //     type: 'utilityCard',
      //   },
      // ],

      railroadsCards: [
        {
          _id: 'railroad-101',
          title: 'Reading Railroad',
          color: '',
          price: 200,
          rent: 25,
          ifTwoCards: 50,
          ifthreeCards: 100,
          ifFourCards: 200,
          mortgage: 100,
          type: 'railroadCard',
        },
        {
          _id: 'railroad-102',
          title: 'Pennsylvania Railroad',
          color: '',
          price: 200,
          rent: 25,
          ifTwoCards: 50,
          ifthreeCards: 100,
          ifFourCards: 200,
          mortgage: 100,
          type: 'railroadCard',
        },
        {
          _id: 'railroad-103',
          title: 'B. & O. Railroad',
          color: '',
          price: 200,
          rent: 25,
          ifTwoCards: 50,
          ifthreeCards: 100,
          ifFourCards: 200,
          mortgage: 100,
          type: 'railroadCard',
        },
        {
          _id: 'railroad-104',
          title: 'Short Line',
          color: '',
          price: 200,
          rent: 25,
          ifTwoCards: 50,
          ifthreeCards: 100,
          ifFourCards: 200,
          mortgage: 100,
          type: 'railroadCard',
        },
      ],

      communityChestCards: [
        {
          _id: 'community-101',
          title: 'Dana Umum',
          description: 'Maju Sampai Start. (Kumpulkan RP.2000)',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-102',
          title: 'Dana Umum',
          description: 'Bayar Asuransi Rp.500',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-103',
          title: 'Dana Umum',
          description: 'KELUAR DARI PENJARA GRATIS. ',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-104',
          title: 'Dana Umum',
          description:
            'Terima Hadiah Undian Rp.2000 dikurangi Pajak final(25%)Rp500 jadi yang diterima Rp.1500',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-105',
          title: 'Dana Umum',
          description: 'Karena Kesalahan Bank Anda Terima RP.1000 ',
          background: '#ffeb43',  
          type: 'communityChestCard',
        },
        {
          _id: 'community-106',
          title: 'Dana Umum',
          description: 'Hari ulang tahun anda terima Rp 2.000',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-107',
          title: 'Dana Umum',
          description: 'PENGEMBALIAN PAJAK PENGHASILAN. KUMPULKAN Rp 200 ',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-108',
          title: 'Dana Umum',
          description: 'Dapat Warisan RP.1000, Tidak Kena Pajak krn bukan objek pajak',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-109',
          title: 'Dana Umum',
          description: 'Dapet Komisi RP.1.000.',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-110',
          title: 'Dana Umum',
          description: 'DANA LIBUR JATUH. KUMPULKAN RP.1000.',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-111',
          title: 'Dana Umum',
          description:
            'KUMPULKAN RP 5.000 DARI SETIAP PEMAIN UNTUK MEMBUKA KURSI MALAM.',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-112',
          title: 'Dana Umum',
          description: "BIAYA DOKTER. BAYAR Rp100",
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-113',
          title: 'Dana Umum',
          description: 'BAYAR RUMAH SAKIT RP.1000.',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-114',
          title: 'Dana Umum',
          description: 'MEMBAYAR PAJAK HIBURAN RP.1000',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-115',
          title: 'Dana Umum',
          description:
            'ANDA DILAYANI UNTUK PERBAIKAN JALAN: BAYAR Rp40 PER RUMAH DAN Rp115 PER HOTEL YANG ANDA MILIKI. ',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-116',
          title: 'Dana Umum',
          description: 'PERGI KE PENJARA. ',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
      ],

      chanceCards: [
        {
          _id: 'chance-201',
          title: 'Kesempatan',
          description: 'MAJU UNTUK "PERGI". (KUMPULKAN Rp 2.000).',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-202',
          title: 'Kesempatan',
          description:
            'MAJU KE KOMPLEK N. JIKA ANDA LULUS, KUMPULKAN Rp 2.000.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-203',
          title: 'Kesempatan',
          description:
            'MAJU KE KOMPLEK F. JIKA ANDA LULUS, KUMPULKAN Rp 2.000 ',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-204',
          title: 'Chance',
          description:
            'TOKEN LANJUTAN KE UTILITAS TERDEKAT. JIKA TIDAK DIMILIKI, ANDA DAPAT MEMBELINYA DARI BANK. JIKA DIMILIKI, LEMBAR DADU DAN BAYAR KEPADA PEMILIK TOTAL 10 (SEPULUH) KALI DARI JUMLAH YANG DIBUAT.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-205',
          title: 'Chance',
          description:
            'MAJU KE RAILROAD TERDEKAT. JIKA TIDAK DIMILIKI, ANDA DAPAT MEMBELINYA DARI BANK. JIKA DIMILIKI, BAYAR KEPADA PEMILIK DUA KALI RETAL YANG MEREKA BERHAK. JIKA RAILROAD TIDAK DIMILIKI, ANDA DAPAT MEMBELINYA DARI BANK.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-206',
          title: 'Kesempatan',
          description: 'Terima Uang Dari Bank Rp.1000',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-207',
          title: 'Kesempatan',
          description: 'KELUAR DARI PENJARA GRATIS.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-208',
          title: 'Kesempatan',
          description: 'MUNDUR 6 LANGKAH.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-209',
          title: 'Kesempatan',
          description:
            'PERGI KE PENJARA. LANGSUNG KE PENJARA. KUMPULKAN Rp.200.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-210',
          title: 'Chance',
          description:
            'LAKUKAN PERBAIKAN UMUM PADA SEMUA PROPERTI ANDA: UNTUK SETIAP RUMAH BAYAR Rp.250, UNTUK SETIAP HOTEL {BAYAR} Rp 1000.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-211',
          title: 'Kesempatan',
          description: 'Bayar Pajak Bumi Dan Bangunan Rp.2000',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-212',
          title: 'Kesempatan',
          description:
            'MELAKUKAN PERJALANAN UNTUK MEMBACA RAILROAD. JIKA ANDA LULUS, KUMPULKAN Rp200. ',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-213',
          title: 'Kesempatan',
          description:
            'BERJALAN-JALAN DI KOMPLEK V. TOKEN LANJUTAN KE JAGAKARSA.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-214',
          title: 'Kesempatan',
          description:
            ' ANDA TELAH TERPILIH KETUA DEWAN. BAYAR SETIAP PEMAIN Rp100. ',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-215',
          title: 'Kesempatan',
          description:
            'BANGUNAN ANDA {DAN} PINJAMAN JATUH. TERIMA / {KUMPULKAN} Rp 150.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-216',
          title: 'Kesempatan',
          description: 'Dapat sumbangan Rp.2500, tidak kena pajak karena bukan objek pajak.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-217',
          title: 'Kesempatan',
          description: 'Melanggar Undang" Pajak Bayar Denda Rp500.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
      ],
    },
  })
}

function _createBoards() {
  let boards = utilService.loadFromStorage(KEY)
  if (!boards || !boards.length) {
    boards = [_createBoard('Board-1')]
    utilService.saveToStorage(KEY, boards)
  }
  return boards
}

function getNewPlayer(name) {
  return {
    _id: utilService.makeId(),
    name: name || 'New-Player-' + utilService.makeId(),
    position: 0,
    propertyCards: [],
    railroadsCards: [],
    utilitiesCards: [],
    communityChestCards: [],
    chanceCards: [],
    isInJail: 0,
    balance: 20.000,
    colorToken: utilService.getRandomColor(),
  }
}

function _createBoard(name) {
  return {
    _id: 'b101',
    title: name,
    createdAt: new Date(),
    tokens: [
      {
        name: 'Scottish Terrier',
      },
      {
        name: 'Battleship',
      },
      {
        name: 'race car mid',
      },
      {
        name: 'Top Hat',
      },
      {
        name: 'Penguin',
      },
      {
        name: 'T-Rex',
      },
      {
        name: 'Cat',
      },
      {
        name: 'Rubber Ducky',
      },
    ],
    houses: 32,
    hotels: 12,
    currPLayer: {
      _id: 'p100',
      name: 'זוהר',
      position: 0,
      propertyCards: [],
      balance: 20000,
      colorToken: 'blue',
    },
    players: [
      {
        _id: 'p100',
        name: 'זוהר',
        position: 0,
        propertyCards: [],
        railroadsCards: [],
        utilitiesCards: [],
        communityChestCards: [],
        chanceCards: [],
        isInJail: 0,
        balance: 20000,
        colorToken: 'blue',
      },
      {
        _id: 'p101',
        name: 'שלומי',
        position: 0,
        propertyCards: [],
        railroadsCards: [],
        utilitiesCards: [],
        chanceCards: [],
        communityChestCards: [],
        isInJail: 0,
        balance: 20000,
        colorToken: '#409eff',
      },
    ],
    tiles: [
      {
        name: 'START',
        players: [
          {
            _id: 'p100',
            name: 'player-0',
            position: 0,
            propertyCards: [],
            balance: 20000,
            colorToken: 'blue',
          },
          {
            _id: 'p101',
            name: 'player-1',
            position: 0,
            propertyCards: [],
            balance: 20000,
            colorToken: '#409eff',
          },
        ],
        owner: null,
        price: 60,
        type: 'go',
      },
      {
        name: 'KOMPLEK A CIRACAS',
        players: [],
        owner: null,
        color: '#562e22',
        price: 2320,
        type: 'city',
      },
      {
        name: 'Community chest',
        players: [],
        owner: null,
        color: '',
        type: 'communityChest',
      },
      {
        name: 'KOMPLEK B SUSUKAN',
        players: [],
        owner: null,
        color: '#562e22',
        price: 4640,
        type: 'city',
      },
      {
        name: 'Pajak penghasilan bayar',
        players: [],
        owner: null,
        color: '',
        price: 1000,
        type: 'tax',
      },
      {
        name: 'Reading Railroad',
        players: [],
        owner: null,
        color: '',
        price: 200,
        type: 'railroad',
      },
      {
        name: 'KOMPLEK C CIJANTUNG',
        players: [],
        owner: null,
        color: '#95b8cb',
        price: 1610,
        type: 'city',
      },
      {
        name: 'Chance',
        players: [],
        owner: null,
        type: 'chance',
      },
      {
        name: 'KOMPLEK D CIPAYUNG',
        players: [],
        owner: null,
        color: '#95b8cb',
        price: 3480,
        type: 'city',
      },
      {
        name: 'KOMPLEK E CILANGKAP',
        players: [],
        owner: null,
        color: '#95b8cb',
        price: 2320,
        type: 'city',
      },
      {
        name: 'jail',
        players: [],
        owner: null,
        type: 'visit',
      },
      {
        name: 'KOMPLEK F CILILITAN',
        players: [],
        owner: null,
        color: '#cb5382',
        price: 1610,
        type: 'city',
      },
      {
        name: 'Pajak Penerang Jalan',
        players: [],
        owner: null,
        color: '',
        price: 150,
        type: 'tax',
      },
      {
        name: 'KOMPLEK G RAMBUTAN',
        players: [],
        owner: null,
        color: '#cb5382',
        price: 3480,
        type: 'city',
      },
      {
        name: 'KOMPLEK H KRAMAT JATI',
        players: [],
        owner: null,
        color: '#cb5382',
        price: 4640,
        type: 'city',
      },
      {
        name: 'Pennsylvania Railroad',
        players: [],
        owner: null,
        color: '',
        price: 200,
        type: 'railroad',
      },
      {
        name: 'KOMPLEK I KALISARI',
        players: [],
        owner: null,
        color: '#ffa600',
        price: 2320,
        type: 'city',
      },
      {
        name: 'Community chest',
        players: [],
        owner: null,
        type: 'communityChest',
      },
      {
        name: 'KOMPLEK J CAKUNG',
        players: [],
        owner: null,
        color: '#ffa600',
        price: 2320,
        type: 'city',
      },
      {
        name: 'KOMPLEK K CAWANG',
        players: [],
        owner: null,
        color: '#ffa600',
        price: 1610,
        type: 'city',
      },
      {
        name: 'Parking',
        players: [],
        owner: null,
        color: '',
        type: 'parking',
      },
      {
        name: 'KOMPLEK L CONDET',
        players: [],
        owner: null,
        color: '#cf3b30',
        price: 5800,
        type: 'city',
      },
      {
        name: 'Chance',
        players: [],
        owner: null,
        color: '',
        type: 'chance',
      },
      {
        name: 'KOMPLEK M PASAR REBO',
        players: [],
        owner: null,
        color: '#cf3b30',
        price: 4640,
        type: 'city',
      },
      {
        name: 'KOMPLEK N PASAR SENIN',
        players: [],
        owner: null,
        color: '#cf3b30',
        price: 2320,
        type: 'city',
      },
      {
        name: 'B. & O. Railroad',
        players: [],
        owner: null,
        color: '',
        price: 200,
        type: 'railroad',
      },
      {
        name: 'KOMPLEK O KP.MELAYU',
        players: [],
        owner: null,
        color: '#d3c11b',
        price: 3480,
        type: 'city',
      },
      {
        name: 'KOMPLEK P CIPINANG',
        players: [],
        owner: null,
        color: '#d3c11b',
        price: 4640,
        type: 'city',
      },
      {
        name: 'Pajak Rokok',
        players: [],
        owner: null,
        color: '',
        price: 150,
        type: 'tax',
      },
      {
        name: 'KOMPLEK Q CILANDAK',
        players: [],
        owner: null,
        color: '#d3c11b',
        price: 2320,
        type: 'city',
      },
      {
        name: 'Send To Jail',
        players: [],
        owner: null,
        color: '',
        type: 'jail',
      },
      {
        name: 'KOMPLEK R PEJATEN',
        players: [],
        owner: null,
        color: '#0ab842',
        price: 3100,
        type: 'city',
      },
      {
        name: 'KOMPLEK S GEDONG',
        players: [],
        owner: null,
        color: '#0ab842',
        price: 3600,
        type: 'city',
      },
      {
        name: 'Community chest',
        players: [],
        owner: null,
        color: '',
        type: 'communityChest',
      },
      {
        name: 'KOMPLEK T PS.MINGGU',
        players: [],
        owner: null,
        color: '#0ab842',
        price: 4640,
        type: 'city',
      },
      {
        name: 'Short Line',
        players: [],
        owner: null,
        color: '',
        price: 200,
        type: 'railroad',
      },
      {
        name: 'Chance',
        players: [],
        owner: null,
        color: '',
        type: 'chance',
      },
      {
        name: 'KOMPLEK U KALIBATA',
        players: [],
        owner: null,
        color: '#2863ad',
        price: 1160,
        type: 'city',
      },
      {
        name: 'Pajak Parkir',
        players: [],
        owner: null,
        color: '',
        price: 200,
        type: 'tax',
      },
      
      {
        name: 'KOMPLEK V JAGAKARSA',
        players: [],
        owner: null,
        color: '#2863ad',
        price: 3380,
        type: 'city',
      },
    ],
    cmpsOrder: [
      'startCmp',
      'tileCmp',
      'communityCmp',
      'tileCmp',
      'incomeCmp',
      'railroadCmp',
      'tileCmp',
      'chanceCmp',
      'tileCmp',
      'tileCmp',
      'jailCmp',
      'tileCmp',
      'electricCmp',
      'tileCmp',
      'tileCmp',
      'railroadCmp',
      'tileCmp',
      'communityCmp',
      'tileCmp',
      'tileCmp',
      'parkingCmp',
      'tileCmp',
      'chanceCmp',
      'tileCmp',
      'tileCmp',
      'railroadCmp',
      'tileCmp',
      'tileCmp',
      'waterWorkCmp',
      'tileCmp',
      'sendToJailCmp',
      'tileCmp',
      'tileCmp',
      'communityCmp',
      'tileCmp',
      'railroadCmp',
      'chanceCmp',
      'tileCmp',
      'luxuryTaxCmp',
      'tileCmp',
    ],
    cards: {
      propertyCards: [
        {
          _id: 'property-101',
          title: 'KOMPLEK A CIRACAS',
          color: '#562e22',
          price: 2320,
          rent: 1100,
          ddp: 2000,
          bphtb: 100,
          ppn: 220,
          pph: 50,
          oneHouse: 500,
          twoHouses: 1100,
          threeHouses: 1650,
          fourHouses: 2200,
          hotel: 250,
          mortgage: 30,
          houseCost: 50,
          hotelCost: 210,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 2,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-102',
          title: 'KOMPLEK B SUSUKAN',
          color: '#562e22',
          rent: 2300,
          ddp: 4000,
          bphtb: 200,
          ppn: 440, 
          pph: 100,
          price: 4640,
          oneHouse: 1000,
          twoHouses: 2200,
          threeHouses: 3300,
          fourHouses: 4400,
          hotel: 450,
          mortgage: 30,
          houseCost: 50,
          hotelCost: 370,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 2,
          houses: 0,
          hotels: 0,
        },

        {
          _id: 'property-103',
          title: 'KOMPLEK C CIJANTUNG',
          color: '#95b8cb',
          price: 1610,
          rent: 600,
          ddp: 1000,
          bphtb: 500,
          ppn: 110,
          pph: 40,
          oneHouse: 400,
          twoHouses: 880,
          threeHouses: 1320,
          fourHouses: 1760,
          hotel: 550,
          mortgage: 50,
          houseCost: 50,
          hotelCost: 450,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-104',
          title: 'KOMPLEK D CIPAYUNG',
          color: '#95b8cb',
          price: 3480,
          rent: 1600,
          ddp: 3000,
          bphtb: 150,
          ppn: 330,
          pph: 80,
          oneHouse: 800,
          twoHouses: 1760,
          threeHouses: 2640,
          fourHouses: 3520,
          hotel: 550,
          mortgage: 50,
          houseCost: 50,
          hotelCost: 450,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-105',
          title: 'KOMPLEK E CILANGKAP',
          color: '#95b8cb',
          price: 2320,
          rent: 1150,
          ddp: 2000,
          bphtb: 100,
          ppn: 220,
          pph: 50,
          oneHouse: 500,
          twoHouses: 1100,
          threeHouses: 1650,
          fourHouses: 2200,
          hotel: 600,
          mortgage: 60,
          houseCost: 50,
          hotelCost: 500,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-106',
          title: 'KOMPLEK F CILILITAN',
          color: '#cb5382',
          price: 1610,
          rent: 550,
          ddp: 1000,
          bphtb: 500,
          ppn: 110,
          pph: 60,
          oneHouse: 600,
          twoHouses: 1320,
          threeHouses: 1980,
          fourHouses: 2640,
          hotel: 750,
          mortgage: 70,
          houseCost: 100,
          hotelCost: 725,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-107',
          title: 'KOMPLEK G RAMBUTAN',
          color: '#cb5382',
          price: 3480,
          rent: 1640,
          ddp: 3000,
          bphtb: 150,
          ppn: 330,
          pph: 110,
          oneHouse: 1100,
          twoHouses: 2420,
          threeHouses: 3630,
          fourHouses: 4840,
          hotel: 750,
          mortgage: 70,
          houseCost: 100,
          hotelCost: 725,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-108',
          title: 'KOMPLEK H KRAMAT JATI',
          color: '#cb5382',
          price: 4640,
          rent: 2320,
          ddp: 4000,
          bphtb: 200,
          ppn: 440,
          pph: 100,
          oneHouse: 1000,
          twoHouses: 2200,
          threeHouses: 3300,
          fourHouses: 4400,
          hotel: 900,
          mortgage: 80,
          houseCost: 100,
          hotelCost: 800,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },

        {
          _id: 'property-109',
          title: 'KOMPLEK I KALISARI',
          color: '#ffa600',
          price: 2320,
          rent: 1110,
          ddp: 2000,
          bphtb: 100,
          ppn: 220,
          pph: 50,
          oneHouse: 500,
          twoHouses: 1100,
          threeHouses: 1650,
          fourHouses: 2200,
          hotel: 950,
          mortgage: 90,
          houseCost: 100,
          hotelCost: 850,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-110',
          title: 'KOMPLEK J CAKUNG',
          color: '#ffa600',
          price: 2320,
          rent: 1110,
          ddp: 2000,
          bphtb: 100,
          ppn: 220,
          pph: 80,
          oneHouse: 800,
          twoHouses: 1760,
          threeHouses: 2640,
          fourHouses: 3520,
          hotel: 950,
          mortgage: 90,
          houseCost: 100,
          hotelCost: 850,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-111',
          title: 'KOMPLEK K CAWANG',
          color: '#ffa600',
          price: 1610,
          rent: 553,
          ddp: 1000,
          bphtb: 500,
          ppn: 110,
          pph: 60,
          oneHouse: 600,
          twoHouses: 1320,
          threeHouses: 1980,
          fourHouses: 2640,
          hotel: 1000,
          mortgage: 100,
          houseCost: 100,
          hotelCost: 900,
          hotelCostNotCalc: 50,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-112',
          title: 'KOMPLEK L CONDET',
          color: '#cf3b30',
          price: 5800,
          rent: 2900,
          ddp: 5000,
          bphtb: 250,
          ppn: 550,
          pph: 150,
          oneHouse: 1500,
          twoHouses: 3300,
          threeHouses: 4950,
          fourHouses: 6600,
          hotel: 1050,
          mortgage: 110,
          houseCost: 150,
          hotelCost: 1025,
          hotelCostNotCalc: 150,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-113',
          title: 'KOMPLEK M PASAR REBO',
          color: '#cf3b30',
          price: 4640,
          rent: 2320,
          ddp: 4000,
          bphtb: 200,
          ppn: 440,
          pph: 100,
          oneHouse: 1000,
          twoHouses: 2200,
          threeHouses: 3300,
          fourHouses: 4400,
          hotel: 1050,
          mortgage: 110,
          houseCost: 150,
          hotelCost: 1025,
          hotelCostNotCalc: 150,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-114',
          title: 'KOMPLEK N PASAR SENIN',
          color: '#cf3b30',
          price: 2320,
          rent: 1110,
          ddp: 2000,
          bphtb: 100,
          ppn: 220,
          pph: 50,
          oneHouse: 500,
          twoHouses: 1100,
          threeHouses: 1650,
          fourHouses: 2200,
          hotel: 1100,
          mortgage: 120,
          houseCost: 150,
          hotelCost: 1075,
          hotelCostNotCalc: 150,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },

        {
          _id: 'property-115',
          title: 'KOMPLEK O KP.MELAYU',
          color: '#d3c11b',
          price: 3480,
          rent: 1690,
          ddp: 3000,
          bphtb: 150,
          ppn: 330,
          pph: 110,
          oneHouse: 1100,
          twoHouses: 2420,
          threeHouses: 3630,
          fourHouses: 4840,
          hotel: 1150,
          mortgage: 130,
          houseCost: 150,
          hotelCost: 1125,
          hotelCostNotCalc: 150,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-116',
          title: 'KOMPLEK P CIPINANG',
          color: '#d3c11b',
          price: 4640,
          rent: 2320,
          ddp: 4000,
          bphtb: 200,
          ppn: 440,
          pph: 100,
          oneHouse: 1000,
          twoHouses: 2200,
          threeHouses: 3300,
          fourHouses: 4400,
          hotel: 1150,
          mortgage: 130,
          houseCost: 150,
          hotelCost: 1125,
          hotelCostNotCalc: 150,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-117',
          title: 'KOMPLEK Q CILANDAK',
          color: '#d3c11b',
          price: 2320,
          rent: 1160,
          ddp: 2000,
          bphtb: 300,
          ppn: 20,
          pph: 100,
          oneHouse: 1000,
          twoHouses: 2200,
          threeHouses: 3300,
          fourHouses: 4400,
          hotel: 1200,
          mortgage: 140,
          houseCost: 150,
          hotelCost: 1175,
          hotelCostNotCalc: 150,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-118',
          title: 'KOMPLEK R PEJATEN',
          color: '#0ab842',
          price: 3100,
          rent: 1550,
          ddp: 2900,
          bphtb: 100,
          ppn: 100,
          pph: 130,
          oneHouse: 1300,
          twoHouses: 2300,
          threeHouses: 3300,
          fourHouses: 4300,
          hotel: 1275,
          mortgage: 150,
          houseCost: 200,
          hotelCost: 1300,
          hotelCostNotCalc: 200,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-119',
          title: 'KOMPLEK S GEDONG',
          color: '#0ab842',
          price: 3600,
          rent: 1750,
          ddp: 3400,
          bphtb: 100,
          ppn: 100,
          pph: 60,
          oneHouse: 600,
          twoHouses: 1200,
          threeHouses: 2200,
          fourHouses: 3300,
          hotel: 1275,
          mortgage: 150,
          houseCost: 200,
          hotelCost: 1300,
          hotelCostNotCalc: 200,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-120',
          title: 'KOMPLEK T PS.MINGGU',
          color: '#0ab842',
          price: 4640,
          rent: 2320,
          ddp: 4000,
          bphtb: 500,
          ppn: 140,
          pph: 110,
          oneHouse: 1100,
          twoHouses: 2200,
          threeHouses: 3300,
          fourHouses: 4400,
          hotel: 1400,
          mortgage: 160,
          houseCost: 200,
          hotelCost: 1400,
          hotelCostNotCalc: 200,
          type: 'propertyCard',
          quantity: 3,
          houses: 0,
          hotels: 0,
        },

        {
          _id: 'property-121',
          title: 'KOMPLEK U KALIBATA',
          color: '#2863ad',
          price: 1160,
          rent: 580,
          ddp: 1000,
          bphtb: 100,
          ppn: 60,
          pph: 120,
          oneHouse: 1200,
          twoHouses: 2400,
          threeHouses: 3500,
          fourHouses: 4600,
          hotel: 1500,
          mortgage: 170,
          houseCost: 200,
          hotelCost: 1500,
          hotelCostNotCalc: 200,
          type: 'propertyCard',
          quantity: 2,
          houses: 0,
          hotels: 0,
        },
        {
          _id: 'property-122',
          title: 'KOMPLEK V JAGAKARSA',
          color: '#2863ad',
          price: 3380,
          rent: 1690,
          ddp: 3000,
          bphtb: 300,
          ppn: 80,
          pph: 110,
          oneHouse: 1100,
          twoHouses: 2250,
          threeHouses: 3250,
          fourHouses: 4350,
          hotel: 2000,
          mortgage: 200,
          houseCost: 200,
          hotelCost: 1900,
          hotelCostNotCalc: 200,
          type: 'propertyCard',
          quantity: 2,
          houses: 0,
          hotels: 0,
        },
      ],

      // utilitiesCards: [
      //   {
      //     _id: 'utility-101',
      //     title: 'Electric Company',
      //     price: 150,
      //     rent: '4 * Dice Roll',
      //     twoAreOwned: '10 * Dice Roll',
      //     mortgage: 75,
      //     background: '#cf8e61',
      //     type: 'utilityCard',
      //   },
      //   {
      //     _id: 'utility-102',
      //     title: 'Pajak Smoking',
      //     price: 150,
      //     rent: '4 * Dice Roll',
      //     twoAreOwned: '10 * Dice Roll',
      //     mortgage: 75,
      //     background: '#f6f4f4',
      //     type: 'utilityCard',
      //   },
      // ],

      railroadsCards: [
        {
          _id: 'railroad-101',
          title: 'Reading Railroad',
          color: '',
          price: 200,
          rent: 25,
          ifTwoCards: 50,
          ifthreeCards: 100,
          ifFourCards: 200,
          mortgage: 100,
          type: 'railroadCard',
        },
        {
          _id: 'railroad-102',
          title: 'Pennsylvania Railroad',
          color: '',
          price: 200,
          rent: 25,
          ifTwoCards: 50,
          ifthreeCards: 100,
          ifFourCards: 200,
          mortgage: 100,
          type: 'railroadCard',
        },
        {
          _id: 'railroad-103',
          title: 'B. & O. Railroad',
          color: '',
          price: 200,
          rent: 25,
          ifTwoCards: 50,
          ifthreeCards: 100,
          ifFourCards: 200,
          mortgage: 100,
          type: 'railroadCard',
        },
        {
          _id: 'railroad-104',
          title: 'Short Line',
          color: '',
          price: 200,
          rent: 25,
          ifTwoCards: 50,
          ifthreeCards: 100,
          ifFourCards: 200,
          mortgage: 100,
          type: 'railroadCard',
        },
      ],

      communityChestCards: [
        {
          _id: 'community-101',
          title: 'Community Chest',
          description: 'Maju Sampai Start. (Kumpulkan RP.2000)',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-102',
          title: 'Community Chest',
          description: 'Life insurance matures - Collect Rp100',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-103',
          title: 'Community Chest',
          description: 'KELUAR DARI PENJARA GRATIS. ',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-104',
          title: 'Community Chest',
          description:
            'You have won second prize in a beauty contest. Collect Rp.10.',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-105',
          title: 'Community Chest',
          description: 'Bank error in your favor. Collect Rp.200. ',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-106',
          title: 'Community Chest',
          description: 'From sale of stock you get Rp50.',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-107',
          title: 'Community Chest',
          description: 'PENGEMBALIAN PAJAK PENGHASILAN. KUMPULKAN Rp 200 ',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-108',
          title: 'Community Chest',
          description: 'Receive for services Rp25.',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-109',
          title: 'Community Chest',
          description: 'Dapet Komisi RP.1.000.',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-110',
          title: 'Community Chest',
          description: 'DANA LIBUR JATUH. KUMPULKAN RP.1000. ',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-111',
          title: 'Community Chest',
          description:
            'Collect Rp50 from every player for opening night seats. ',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-112',
          title: 'Community Chest',
          description: "Doctor's fees. Pay Rp50.",
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-113',
          title: 'Community Chest',
          description: 'Pay hospital Rp100.',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-114',
          title: 'Community Chest',
          description: 'Pay school tax of Rp150',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-115',
          title: 'Community Chest',
          description:
            'You are assessed for street repairs: Pay Rp40 per house and Rp115 per hotel you own. ',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
        {
          _id: 'community-116',
          title: 'Community Chest',
          description: 'PERGI KE PENJARA. ',
          background: '#ffeb43',
          type: 'communityChestCard',
        },
      ],

      chanceCards: [
        {
          _id: 'chance-201',
          title: 'Chance',
          description: 'MAJU UNTUK "PERGI". (KUMPULKAN RP 2.000).',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-202',
          title: 'Chance',
          description:
            'Advance to Illinois Ave. {Komplek}. If you pass Go, collect Rp200.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-203',
          title: 'Chance',
          description:
            'Advance to KOMPLEK F CILILITAN. If you pass Go, collect Rp200. ',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-204',
          title: 'Chance',
          description:
            'Advance token to the nearest Utility. If unowned, you may buy it from the Bank. If owned, throw dice and pay owner a total 10 (ten) times the amount thrown. ',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-205',
          title: 'Chance',
          description:
            'Advance to the nearest Railroad. If unowned, you may buy it from the Bank. If owned, pay owner twice the re tal to which they are otherwise entitled. If Railroad is unowned, you may buy it from the Bank.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-206',
          title: 'Chance',
          description: 'Bank pays you dividend of Rp50. ',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-207',
          title: 'Chance',
          description: 'KELUAR DARI PENJARA GRATIS.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-208',
          title: 'Chance',
          description: 'MUNDUR 6 LANGKAH',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-209',
          title: 'Chance',
          description:
            'Go to Jail. Go directly to Jail. Do not pass GO, do not collect Rp200.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-210',
          title: 'Chance',
          description:
            'Make general repairs on all your property: For each house pay Rp25, For each hotel {pay} Rp100.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-211',
          title: 'Chance',
          description: 'Bayar Pajak Bumi Dan Bangunan Rp.2000',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-212',
          title: 'Chance',
          description:
            'Take a trip to Reading Railroad.  If you pass Go, collect Rp200. ',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-213',
          title: 'Chance',
          description:
            'Take a walk on the Boardwalk. Advance token to Boardwalk. ',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-214',
          title: 'Chance',
          description:
            ' You have been elected Chairman of the Board. Pay each player Rp500. ',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-215',
          title: 'Chance',
          description:
            'Your building {and} loan matures. Receive {Collect} Rp150.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
        {
          _id: 'chance-216',
          title: 'Chance',
          description: 'You have won a crossword competition. Collect Rp100.',
          background: '#ff5c00',
          type: 'chanceCards',
        },
      ],
    },
  }
}
